services:
  mkdocs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mkdocs
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "${PUERTO}:${PUERTO}"
    command: mkdocs serve -a 0.0.0.0:${PUERTO} -t ${TEMA}
    restart: unless-stopped
